version: "3.9"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase

  redis:
    image: redis:latest
    container_name: redis_db

volumes:
  pgdata:
